# Generated by Django 4.0.4 on 2022-04-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_alter_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='due_by',
            field=models.DateTimeField(null=True),
        ),
    ]
