# Generated by Django 4.0.4 on 2022-04-15 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_note_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='latitude',
            field=models.DecimalField(decimal_places=5, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='longitude',
            field=models.DecimalField(decimal_places=5, max_digits=8, null=True),
        ),
    ]
